export const SN_CREDIT = 'credit'
export const CREDIT_SET_BANKS = SN_CREDIT + '/CREDIT_SET_BANKS'
export const CREDIT_SET_SELECTED_BANK = SN_CREDIT + '/CREDIT_SET_SELECTED_BANK'
export const CREDIT_SET_FIELDS = SN_CREDIT + '/CREDIT_SET_FIELDS'
